WebApp/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp.Models;
using WebApp.ViewModel;

namespace WebApp.Controllers
{
    public class CustomerController : Controller
    {
        public ActionResult Index()
        {
            CustomerClient CC = new CustomerClient();
            ViewBag.listCustomers = CC.FindAll();
            return View();
        }
        [HttpGet]
        public ActionResult Create()
        {
            CustomerClient CC = new CustomerClient();
            ViewBag.listCustomers = CC.FindAll();
            //return View();
            return View("Create");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(OrderViewModel cvm)
        {
            if (ModelState.IsValid)
            {
                CustomerClient CC = new CustomerClient();
                CC.Create(cvm.customer);
            }
            return RedirectToAction("Index");

        }

        public ActionResult Delete(int id)
        {
            CustomerClient CC = new CustomerClient();
            CC.Delete(id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            CustomerClient CC = new CustomerClient();
            OrderViewModel CVM = new OrderViewModel();
            CVM.customer = CC.find(id);
            return View("Edit", CVM);
        }
        [HttpPost]
        public ActionResult Edit(OrderViewModel CVM)
        {
            CustomerClient CC = new CustomerClient();
            CC.Edit(CVM.customer);
            return RedirectToAction("Index");
        }
    }
}

WebApp/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp.Models;
using WebApp.ViewModel;

namespace WebApp.Controllers
{
    public class OrderController : Controller
    {
        public ActionResult Index()
        {
            OrderClient CC = new OrderClient();
            ViewBag.listOrders = CC.findAll();
            return View();
        }
        [HttpGet]
        public ActionResult Create()
        {
            CustomerClient CX = new CustomerClient();
            ViewBag.listCustomers = CX.FindAll();
            ProductClient PC = new ProductClient();
            ViewBag.listProducts = PC.FindAll();
            //return View();
            return View("Create");
        }
        [HttpPost]
        public ActionResult Create(OrderViewModel cvm)
        {
            OrderClient CC = new OrderClient();
            CC.Create(cvm.order);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            OrderClient CC = new OrderClient();
            CC.Delete(id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            CustomerClient CX = new CustomerClient();
            ViewBag.listCustomers = CX.FindAll();
            ProductClient PC = new ProductClient();
            ViewBag.listProducts = PC.FindAll();

            OrderClient CC = new OrderClient();
            OrderViewModel CVM = new OrderViewModel();
            CVM.order = CC.find(id);
            return View("Edit", CVM);
        }
        [HttpPost]
        public ActionResult Edit(OrderViewModel CVM)
        {
            OrderClient CC = new OrderClient();
            CC.Edit(CVM.order);
            return RedirectToAction("Index");
        }
    }
}

WebApp/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp.Models;
using WebApp.ViewModel;

namespace WebApp.Controllers
{
    public class ProductController : Controller
    {
        public ActionResult Index()
        {
            ProductClient PC = new ProductClient();
            ViewBag.listProducts = PC.FindAll();
            return View();
        }
        [HttpGet]
        public ActionResult Create()
        {
            ProductClient PC = new ProductClient();
            ViewBag.listProducts = PC.FindAll();
            //return View();
            return View("Create");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(OrderViewModel cvm)
        {
            if (ModelState.IsValid)
            {
                ProductClient PC = new ProductClient();
                PC.Create(cvm.product);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            ProductClient PC = new ProductClient();
            PC.Delete(id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            ProductClient PC = new ProductClient();
            OrderViewModel CVM = new OrderViewModel();
            CVM.product = PC.find(id);
            return View("Edit", CVM);
        }
        [HttpPost]
        public ActionResult Edit(OrderViewModel CVM)
        {
            ProductClient PC = new ProductClient();
            PC.Edit(CVM.product);
            return RedirectToAction("Index");
        }
    }
}

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Data Customer", "Index", "Customer", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Data Product", "Index", "Product", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Order Transaction", "Index", "Order", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>